global:
  - CC_REPORTER_ID=db93c8757baf4dd6272963ffa6f16fa3fdb0b9850a81f9bd33d28e940f025228

language: java

jdk: openjdk13

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
  - unzip -qq apache-maven-3.5.4-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo fc-cache -f -v

install: /bin/true

script:
  - mvn clean install -Pci
  - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./target/coverage-reports/jacoco.xml --input-type jacoco

after_success:
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
  - bash <(curl -s https://codecov.io/bash)
