env:
  global:
    - CODECOV_TOKEN=d9501c65-0569-4f71-ae65-c6791f7c4b79
    - CC_TEST_REPORTER_ID=db93c8757baf4dd6272963ffa6f16fa3fdb0b9850a81f9bd33d28e940f025228

language: java

jdk: openjdk13

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
  - unzip -qq apache-maven-3.5.4-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install: /bin/true

script:
  - mvn clean install -Pci

after_script:
  - find . -name jacoco.xml
  - JACOCO_SOURCE_PATH=./core-commons/src/main/java ./cc-test-reporter format-coverage ./core-commons/target/coverage-reports/jacoco.xml -t jacoco -o ./target/coverage/codeclimate.core-commons.json
  - JACOCO_SOURCE_PATH=./core-parsers/src/main/java ./cc-test-reporter format-coverage ./core-parsers/target/coverage-reports/jacoco.xml -t jacoco -o ./target/coverage/codeclimate.core-parsers.json
  - JACOCO_SOURCE_PATH=./edi-datanorm/src/main/java ./cc-test-reporter format-coverage ./edi-datanorm/target/coverage-reports/jacoco.xml -t jacoco -o ./target/coverage/codeclimate.edi-datanorm.json
  - JACOCO_SOURCE_PATH=./edi-edifact/src/main/java ./cc-test-reporter format-coverage ./edi-edifact/target/coverage-reports/jacoco.xml -t jacoco -o ./target/coverage/codeclimate.edi-edifact.json
  - JACOCO_SOURCE_PATH=./edi-vda/src/main/java ./cc-test-reporter format-coverage ./edi-vda/target/coverage-reports/jacoco.xml -t jacoco -o ./target/coverage/codeclimate.edi-vda.json
  - ./cc-test-reporter sum-coverage ./target/coverage/codeclimate.*.json -p 5
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage -i ./target/coverage/codeclimate.json; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
